package com.nihongo.conversation.domain.model

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Cached AI response for a conversation pattern
 * Stores pre-generated responses to avoid API calls
 */
@Entity(
    tableName = "cached_responses",
    foreignKeys = [
        ForeignKey(
            entity = ConversationPattern::class,
            parentColumns = ["id"],
            childColumns = ["patternId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index("patternId")]
)
data class CachedResponse(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    // Link to pattern
    val patternId: Long,

    // Response content
    val response: String, // The AI response text
    val variation: Int = 0, // Variation number (0-99 for 100 variations per pattern)

    // Response metadata
    val complexityScore: Int = 0, // Difficulty score of the response
    val characterCount: Int = response.length,
    val wordCount: Int = response.split("\\s+".toRegex()).size,

    // Usage statistics
    val usageCount: Long = 0, // How many times this specific response has been used
    val lastUsedTimestamp: Long = System.currentTimeMillis(),
    val userSatisfactionScore: Float = 0.0f, // Based on follow-up engagement

    // Quality control
    val isVerified: Boolean = false, // Whether this response has been manually verified
    val generatedByApi: Boolean = true, // true=generated by API, false=manually created

    // Metadata
    val createdAt: Long = System.currentTimeMillis()
)
